export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAILED = 'FETCH_LOCATION_FAILED';

export const FETCH_BANNER_ASIDE = 'FETCH_BANNER_ASIDE';
export const FETCH_BANNER_ASIDE_SUCCESS = 'FETCH_BANNER_ASIDE_SUCCESS';
export const FETCH_BANNER_ASIDE_FAILED = 'FETCH_BANNER_ASIDE_FAILED';

export const FETCH_GENERAL_INFORMATION = 'FETCH_GENERAL_INFORMATION';
export const FETCH_GENERAL_INFORMATION_SUCCESS = 'FETCH_GENERAL_INFORMATION_SUCCESS';
export const FETCH_GENERAL_INFORMATION_FAILED = 'FETCH_GENERAL_INFORMATION_FAILED';
